spring:
  datasource:  
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:

security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: spcbrasil
    key-pair-alias: spcbrasil.org.br
    key-pair-password: spcbrasil
datasource:
    oracle:
      connectionFactoryClassName: oracle.jdbc.pool.OracleDataSource
      keyfile: ${app.store}/key/spcjava.cer
      passwordfile: ${app.store}/key/usrjava-db-pwd-DEV.key
      connectionpoolname: cadpos-datasource-pool
      minPoolSize: 1
      maxPoolSize: 30
      jdbcUrl: jdbc:oracle:thin:@//db-dev.spcdc.br:1521/SPCDESSP
      jdbcUser: usrjava
      hibernateShowSQL: false

hibernate:
  hbm2ddl:
    auto: none
  show-sql: false
