app: 
  auth: 
    driver: h2
  module: 
    h2: 
      enabled: true
    oracle:
      enabled: true
          
spring:
  datasource:
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  allowed:
     resources: /h2-console/**
security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: spcbrasil
    key-pair-alias: spcbrasil.org.br
    key-pair-password: spcbrasil
docker:
  registry: yure.teste.com

datasource:
    oracle:
      connectionFactoryClassName: oracle.jdbc.pool.OracleDataSource
      keyfile: ${app.store}/key/spcjava.cer
      passwordfile: ${app.store}/key/usrjava-db-pwd-DEV.key
      connectionpoolname: cadpos-datasource-pool
      minPoolSize: 1
      maxPoolSize: 30
      jdbcUrl: jdbc:oracle:thin:@//db-dev.spcdc.br:1521/SPCDESSP
      jdbcUser: usrjava
      message: teste
      hibernateShowSQL: true

hibernate:
  hbm2ddl:
    auto: validate
  show-sql: true

logging:
  level:
    root: DEBUG

  