ALTER TABLE SPCJAVA.SENHA_OPERADOR MODIFY DES_SENHA VARCHAR(200);
ALTER TABLE SPCJAVA.SENHA_OPERADOR MODIFY DES_SENHA_HOST_HOST_4 VARCHAR(200);
ALTER TABLE SPCJAVA.SENHA_OPERADOR MODIFY DES_SENHA_HOST_HOST_5 VARCHAR(200);
ALTER TABLE SPCJAVA.SENHA_OPERADOR MODIFY DES_SENHA_HOST_HOST_6 VARCHAR(200);
ALTER TABLE SPCJAVA.SENHA_OPERADOR MODIFY DES_SENHA_HOST_HOST_7 VARCHAR(200);
